### ISSUE TITLE
Tensorman will not install with docker-ce present on machine

### ISSUE THREAD

**Issue by zaphod80013** [pop-os/tensorman#11]
For compatibility with my work machine I install docker from the docker repository rather than the pop-os repo. Their package is called docker-ce. So I have a perfectly functional docker install present but cant install tensorman due to its dependency on docker.io which, it turns out, conflicts with docker-ce.  I tried creating a dummy package to satisfy the dependency on docker.io but it wouldn't install because docker-ce-cli conflicts with docker.io.

would it be possible to make tensorman dependent on either docker.io or docker.ce?

**Comment by mmstick** [comment]
I can fix this. I will push it today.

**Comment by zaphod80013** [comment]
Thanks, tied up having a new furnace installed yesterday and only just seen this. I will take a backup then purge docker.io & tensorman then do a test install either today or tomorrow. I did just notice I fat fingered the package name in the last sentence it should be docker-ce (with a hyphen) hope you caught that.

**Comment by mmstick** [comment]
Yes, I knew the package name. You can verify this with:

```
# apt-cache depends tensorman
tensorman
 |Depends: docker.io
  Depends: <docker-ce>
  Suggests: nvidia-container-runtime
```

If `docker-ce` is installed, then `docker.io` will not be installed. Otherwise, if nothing is installed, `docker.io` is installed. Since 19.10 released with the latest version of Docker, `docker-ce` isn't necessary to use GPU compute.

**Comment by zaphod80013** [comment]
Looks good, thx, I did some basic testing; purged tensorman & all docker related components, did a dry-run install of tensorman which pulled in docker.io installed my dummy package to satisfy docker.io and retried the dry-run, it only wanted to install tensorman. The did a real install of docker-ce followed by tensorman, all was fine. Still in the middle of a machine rebuild and, as yet, have no experience of tensorman or tensorflow so I didn't attempt to test beyond the install. 

Assumptions are dangerous but since you were able to update both Git and the apt repo so quickly I'm guessing you work for System76, as you may guess from my UserID I live in metro Denver area. And have attended release parties at both 16th & Champa and the new facility. The System76 team are an awesome bunch of folks. If I didn't work with an equally cool bunch at a Denver base, cyber-security related, company I'd probably be knocking on your door :-)

**Comment by zaphod80013** [comment]
I'm closing this issue as resolved.

**Comment by mmstick** [comment]
>  I'm guessing you work for System76

Yes, I'm the maintainer of Pop!_OS, and this is a project that I developed for our Tensorflow customers. Docker's the only reliable way to get Tensorflow working on 19.10, so this had to be developed as a path forward from 19.04. Any sort of feature and bug reports on this project will see quick action from me, since it's an important area for Pop!_OS.
