### ISSUE TITLE
Not able to launch custom image

### ISSUE THREAD

**Issue by adschem** [pop-os/tensorman#17]
Hello, 
To run the container that generates the image I have used: 
tensorman run --gpu --python3 --root --name NAME_IS bash

I have created a custom image as per the instructions, saved the image using (in a new terminal window):

`tensorman save NAME_IS NAME_IS_IMG` 

Then when I try to run the image I get an error saying the image is not found. Attached is a screen shot with tensorman list and the error, any ideas how I can get this working? 

![image](https://user-images.githubusercontent.com/14344249/74519978-a08db780-4f0e-11ea-8a6f-9474e29912e7.png)

Thanks,
A

**Comment by mmstick** [comment]
This works for me. It looks like zsh is trying to execute `=NAME_IS_IMG` as a command (?). There should have been error from tensorman about not being able to find the image, rather than an error from zsh.

**Comment by adschem** [comment]
Any thoughts how to resolve this? sorry new to using tensorman

**Comment by mmstick** [comment]
Since it appears to be an error from zsh, have you tried quoting `=NAME_IS_IMG`, or running that command in Bash?

**Comment by adschem** [comment]
running `tensorman '=NAME_IS_IMG'  run --gpu bash` works perfectly! Thank you v. much
