### ISSUE TITLE
Tensorman update with the new version of Tensorflow

### ISSUE THREAD

**Issue by kpech21** [pop-os/tensorman#26]
Could you tell me if there are plans to update Tensorman with one the the last Tensorflow versions (2.3.1 or 2.4.0)?

Thank you in advance!

**Comment by ids1024** [comment]
Tensorman uses docker, and the official tensorflow docker images. You should be able to use any image there: https://hub.docker.com/r/tensorflow/tensorflow/tags

**Comment by ids1024** [comment]
It doesn't look like 2.4.0 is released: https://github.com/tensorflow/tensorflow/tags. But 2.4.0rc3 seems to be on docker.
