### ISSUE TITLE
"exec: \"./prog.py\": permission denied": unknown.

### ISSUE THREAD

**Issue by phobrain** [pop-os/tensorman#5]
I'm learning how to hello world with tensorman, on just-upgraded Pop!_OS: 19.0:

$ tensorman pull
"docker" "pull" "tensorflow/tensorflow:latest-gpu-py3"
latest-gpu-py3: Pulling from tensorflow/tensorflow
Digest: sha256:2089bcbf3a7b9e41d7c4be3971874598d04fd0b9190aca924d634053adca41c7
Status: Image is up to date for tensorflow/tensorflow:latest-gpu-py3
docker.io/tensorflow/tensorflow:latest-gpu-py3
$ tensorman run --gpu --python3 ./p2.py
"docker" "run" "-u" "1000:1000" "--runtime=nvidia" "-it" "--rm" "-v" "/home/me/ml/keras/pp2:/project" "-w" "/project" "tensorflow/tensorflow:latest-gpu-py3" "./p2.py"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"./p2.py\": permission denied": unknown.
$ ls -l p2.py 
-rw-r--r-- 1 me megrp 55946 Oct 23 16:39 p2.py

Same using full path to file. Last night it seemed to work except it was using python3.6 and couldn't find numpy no matter what I tried. Slept and now this after fixing cmd line I think.

[author comment below is simple solution, own simultaneous/editing debug left here for detail]

Is it really wanting to *execute* the .py file? Trying chmod +x:

$ chmod +x p2.py 
$ tensorman run --gpu --python3 ./p2.py
"docker" "run" "-u" "1000:1000" "--runtime=nvidia" "-it" "--rm" "-v" "/home/me/ml/keras/pp2:/project" "-w" "/project" "tensorflow/tensorflow:latest-gpu-py3" "./p2.py"
standard_init_linux.go:211: exec user process caused "exec format error"

... adding to the top of p2.py gets it to run:

#!/usr/bin/python3

And now I'm back to my original issue. Likely this is just due to never using docker before, but the error signatures don't lead to answers so hard to say. Another possibility could be Sys76 laptop integration, seeing as it's a new release. Last one went to python3.7, hence the oddness of seeing 3.6 in the sys.path in python:

exec: /usr/bin/python3
path: ['/project', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']

**Comment by mmstick** [comment]
Try `chmod +x p2.py` and run it again, or `tensorman run --gpu --python3 python3 -- p2.py`

**Comment by phobrain** [comment]
> tensorman run --gpu --python3 -- p2.py

Aha, that's what was getting it to run last night, except I didn't have '--' before python3 from copying a bad example maybe, so today moved the free '--' there and thereby flipped to direct execution in fixing that. 

This problem is solved and should help anyone else who hits it, so will close and file on the missing pkg issue.
