### ISSUE TITLE
tensorman failing on gpu with error "Unknown runtime specified nvidia"

### ISSUE THREAD

**Issue by schwab** [pop-os/tensorman#8]
With ubuntu 19.10 pop!os, I installed tensorman which resulted in docker 19.03.2 being installed....
```
 docker --version
Docker version 19.03.2, build 6a30dfca03
```

However this fails:

``` 
tensorman run --gpu bash
 ```  
with: 
```
tensorman run --gpu bash
"docker" "run" "-u" "1000:1000" "--runtime=nvidia" "-it" "--rm" "-v" "/home/michaelschwab/pyimagesearch:/project" "-w" "/project" "tensorflow/tensorflow:latest-gpu" "bash"
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.
```

Shoudn't it be using --gpus all instead of --runtime=nvidia?

Note: 
I verified this command does work...
``` 
docker run -it -u 1000:1000  --rm --gpus all bash
```

**Comment by mmstick** [comment]
Did you install `nvidia-container-runtime`?

**Comment by schwab** [comment]
Yes, that's installed too...
Confirmed with ...
```
sudo apt install nvidia-container-runtime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nvidia-container-runtime is already the newest version (3.1.4-0pop1~1569270714~19.10~2ea45f8).
The following packages were automatically installed and are no longer required:
  pop-upgrade wmdocker
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by mmstick** [comment]
Have you restarted since installing it?

**Comment by schwab** [comment]
Yes, and I just restarted again to be sure.  It appears to be passing the wrong parameter to the docker command since --runtime=nvidia  is deprecated in the current version of docker.  I think it should be --gpus all, which works fine on the terminal.

**Comment by mmstick** [comment]
With the version of Docker in 19.10? `=nvidia` should still work.

![Screenshot from 2019-10-29 08-27-53](https://user-images.githubusercontent.com/4143535/67776527-0882c580-fa26-11e9-9db8-1c5a69d180c9.png)

**Comment by mmstick** [comment]
The most recent update is using `--gpus=all` now.
