### ISSUE TITLE
please track releases on github

### ISSUE THREAD

**Issue by thefenriswolf** [pop-os/tensorman#9]
I am trying to package tensorman for Nixpkgs. It would make my life a whole lot easier if tensormans releases (even if it's a 0.1.0) were tagged so I could pull specific milestones

**Comment by mmstick** [comment]
I will tag a release today, but be wary that I may tag releases often.

**Comment by mmstick** [comment]
I've tagged 0.1.0, and released on Crates.io

**Comment by thefenriswolf** [comment]
thank you so much, I will try my best to keep up with the releases

**Comment by thefenriswolf** [comment]
tensorman is now available from nixpkgs-unstable: https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=tensorman
